dado = 10 
print(f"Conteudo da variaveal dado: {dado}")

dado += 1 # dado = dado + 1
print(f"Conteudo da variavel dado, depois do incremento: {dado} ")

dado -= 1 # dado = dado - 1 
print(f"contudo da variavel dado, dpois  do decremento: {dado}")

# MULTIPLICAÇÃO E DIVISÃO 

dado *= 1 # dado = dado * 2
print(f"Conteudo da variavel dado, depois do incremento: {dado} ")

dado /= 1 # dado = dado / 2 
print(f"contudo da variavel dado, dpois  do decremento: {dado}")
